export const baseUrl = "http://localhost:6767/api/v1";

export const config = {
    headers: {
        "Access-Control-Allow-Origin": "*",
        "Content-Type": "application/json",
    },
    withCredentials: true,
};

export const languages = [
    "Assamese",
    "English",
    "Hindi",
    "Bengali",
    "Gujrati",
    "Tamil",
    "Telegu",
    "Chinese",
    "French",
    "Japanese",
];

export const navlinks = [
    { name: "Home", path: "/" },
    { name: "My profile", path: "/profile/view" },
    { name: "My bookmarks", path: "/bookmarks" },
    { name: "My applications", path: "/applications" },
    { name: "My Resume", path: "/resume" },
    { name: "My Preferences", path: "/my/preferences" },
];

export const manageAccount = [
    { name: "Change password", path: "/change/password" },
    { name: "Change email", path: "/update/email" },
    { name: "Delete account", path: "/acc/delete" },
    { name: "Logout", path: "/logout" },
];

export const career_fields = [
    "Frontend Development",
    "Backend Development",
    "Full-Stack Development",
    "Mobile App Development",
    "Game Development",
    "DevOps Engineering",
    "Data Analysis",
    "Machine Learning Engineering",
    "Data Visualization",
    "Business Intelligence",
    "Big Data Engineering",
    "Graphic Design",
    "UI/UX Design",
    "Web Design",
    "Motion Graphics",
    "Product Design",
    "Digital Marketing",
    "Social Media Marketing",
    "Content Marketing",
    "Search Engine Optimization (SEO)",
    "Advertising Copywriting",
    "Project Management",
    "Human Resources Management",
    "Financial Analysis",
    "Management Consulting",
    "Operations Management",
    "Medicine",
    "Medical Research",
    "Healthcare Administration",
    "Medical Writing",
    "Healthcare IT",
    "Civil Engineering",
    "Electrical Engineering",
    "Mechanical Engineering",
    "Aerospace Engineering",
    "Chemical Engineering",
    "Teaching",
    "Corporate Training",
    "Curriculum Development",
    "Online Course Instruction",
    "Educational Technology (EdTech)",
    "Writing",
    "Film and Video Production",
    "Photography",
    "Music Production",
    "Performing Arts",
    "Lawyer",
    "Law Enforcement Officer",
    "Legal Consultant",
    "Paralegal",
    "Compliance Officer",
];
